// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datacenter.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGameListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameListReq) Reset()         { *m = GetGameListReq{} }
func (m *GetGameListReq) String() string { return proto.CompactTextString(m) }
func (*GetGameListReq) ProtoMessage()    {}
func (*GetGameListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{0}
}

func (m *GetGameListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameListReq.Unmarshal(m, b)
}
func (m *GetGameListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameListReq.Marshal(b, m, deterministic)
}
func (m *GetGameListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameListReq.Merge(m, src)
}
func (m *GetGameListReq) XXX_Size() int {
	return xxx_messageInfo_GetGameListReq.Size(m)
}
func (m *GetGameListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameListReq proto.InternalMessageInfo

type GetGameListResp struct {
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	// 热门游戏的symbol
	Hot []string `protobuf:"bytes,2,rep,name=hot,proto3" json:"hot,omitempty"`
	// 新游戏
	New []string `protobuf:"bytes,3,rep,name=new,proto3" json:"new,omitempty"`
	// 推荐游戏
	Recommend []string `protobuf:"bytes,4,rep,name=recommend,proto3" json:"recommend,omitempty"`
	// 所有游戏及状态
	All                  []*GetGameListResp_GameInfoItem `protobuf:"bytes,5,rep,name=all,proto3" json:"all,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetGameListResp) Reset()         { *m = GetGameListResp{} }
func (m *GetGameListResp) String() string { return proto.CompactTextString(m) }
func (*GetGameListResp) ProtoMessage()    {}
func (*GetGameListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{1}
}

func (m *GetGameListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameListResp.Unmarshal(m, b)
}
func (m *GetGameListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameListResp.Marshal(b, m, deterministic)
}
func (m *GetGameListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameListResp.Merge(m, src)
}
func (m *GetGameListResp) XXX_Size() int {
	return xxx_messageInfo_GetGameListResp.Size(m)
}
func (m *GetGameListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameListResp proto.InternalMessageInfo

func (m *GetGameListResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func (m *GetGameListResp) GetHot() []string {
	if m != nil {
		return m.Hot
	}
	return nil
}

func (m *GetGameListResp) GetNew() []string {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *GetGameListResp) GetRecommend() []string {
	if m != nil {
		return m.Recommend
	}
	return nil
}

func (m *GetGameListResp) GetAll() []*GetGameListResp_GameInfoItem {
	if m != nil {
		return m.All
	}
	return nil
}

type GetGameListResp_GameInfoItem struct {
	// 游戏标志
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// 游戏状态 1 正常 2 维护
	State                int32    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameListResp_GameInfoItem) Reset()         { *m = GetGameListResp_GameInfoItem{} }
func (m *GetGameListResp_GameInfoItem) String() string { return proto.CompactTextString(m) }
func (*GetGameListResp_GameInfoItem) ProtoMessage()    {}
func (*GetGameListResp_GameInfoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{1, 0}
}

func (m *GetGameListResp_GameInfoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameListResp_GameInfoItem.Unmarshal(m, b)
}
func (m *GetGameListResp_GameInfoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameListResp_GameInfoItem.Marshal(b, m, deterministic)
}
func (m *GetGameListResp_GameInfoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameListResp_GameInfoItem.Merge(m, src)
}
func (m *GetGameListResp_GameInfoItem) XXX_Size() int {
	return xxx_messageInfo_GetGameListResp_GameInfoItem.Size(m)
}
func (m *GetGameListResp_GameInfoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameListResp_GameInfoItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameListResp_GameInfoItem proto.InternalMessageInfo

func (m *GetGameListResp_GameInfoItem) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetGameListResp_GameInfoItem) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type UserLockReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLockReq) Reset()         { *m = UserLockReq{} }
func (m *UserLockReq) String() string { return proto.CompactTextString(m) }
func (*UserLockReq) ProtoMessage()    {}
func (*UserLockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{2}
}

func (m *UserLockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLockReq.Unmarshal(m, b)
}
func (m *UserLockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLockReq.Marshal(b, m, deterministic)
}
func (m *UserLockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLockReq.Merge(m, src)
}
func (m *UserLockReq) XXX_Size() int {
	return xxx_messageInfo_UserLockReq.Size(m)
}
func (m *UserLockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLockReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserLockReq proto.InternalMessageInfo

func (m *UserLockReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserLockResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLockResp) Reset()         { *m = UserLockResp{} }
func (m *UserLockResp) String() string { return proto.CompactTextString(m) }
func (*UserLockResp) ProtoMessage()    {}
func (*UserLockResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{3}
}

func (m *UserLockResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLockResp.Unmarshal(m, b)
}
func (m *UserLockResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLockResp.Marshal(b, m, deterministic)
}
func (m *UserLockResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLockResp.Merge(m, src)
}
func (m *UserLockResp) XXX_Size() int {
	return xxx_messageInfo_UserLockResp.Size(m)
}
func (m *UserLockResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLockResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserLockResp proto.InternalMessageInfo

func (m *UserLockResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type UserUnLockReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUnLockReq) Reset()         { *m = UserUnLockReq{} }
func (m *UserUnLockReq) String() string { return proto.CompactTextString(m) }
func (*UserUnLockReq) ProtoMessage()    {}
func (*UserUnLockReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{4}
}

func (m *UserUnLockReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUnLockReq.Unmarshal(m, b)
}
func (m *UserUnLockReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUnLockReq.Marshal(b, m, deterministic)
}
func (m *UserUnLockReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUnLockReq.Merge(m, src)
}
func (m *UserUnLockReq) XXX_Size() int {
	return xxx_messageInfo_UserUnLockReq.Size(m)
}
func (m *UserUnLockReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUnLockReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUnLockReq proto.InternalMessageInfo

func (m *UserUnLockReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserUnLockReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserUnLockResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUnLockResp) Reset()         { *m = UserUnLockResp{} }
func (m *UserUnLockResp) String() string { return proto.CompactTextString(m) }
func (*UserUnLockResp) ProtoMessage()    {}
func (*UserUnLockResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{5}
}

func (m *UserUnLockResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUnLockResp.Unmarshal(m, b)
}
func (m *UserUnLockResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUnLockResp.Marshal(b, m, deterministic)
}
func (m *UserUnLockResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUnLockResp.Merge(m, src)
}
func (m *UserUnLockResp) XXX_Size() int {
	return xxx_messageInfo_UserUnLockResp.Size(m)
}
func (m *UserUnLockResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUnLockResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserUnLockResp proto.InternalMessageInfo

func (m *UserUnLockResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type GetRecordsReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordsReq) Reset()         { *m = GetRecordsReq{} }
func (m *GetRecordsReq) String() string { return proto.CompactTextString(m) }
func (*GetRecordsReq) ProtoMessage()    {}
func (*GetRecordsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{6}
}

func (m *GetRecordsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsReq.Unmarshal(m, b)
}
func (m *GetRecordsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsReq.Marshal(b, m, deterministic)
}
func (m *GetRecordsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsReq.Merge(m, src)
}
func (m *GetRecordsReq) XXX_Size() int {
	return xxx_messageInfo_GetRecordsReq.Size(m)
}
func (m *GetRecordsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsReq proto.InternalMessageInfo

func (m *GetRecordsReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetRecordsReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetRecordsReq) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RecordItem struct {
	AgentId              uint32       `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	UserId               uint32       `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Bet                  float64      `protobuf:"fixed64,3,opt,name=bet,proto3" json:"bet,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CurrencySymbol       string       `protobuf:"bytes,5,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	BaseBet              float64      `protobuf:"fixed64,6,opt,name=base_bet,json=baseBet,proto3" json:"base_bet,omitempty"`
	Win                  float64      `protobuf:"fixed64,7,opt,name=win,proto3" json:"win,omitempty"`
	Rtp                  float64      `protobuf:"fixed64,8,opt,name=rtp,proto3" json:"rtp,omitempty"`
	PlayedDate           int64        `protobuf:"varint,9,opt,name=playedDate,proto3" json:"playedDate,omitempty"`
	RoundID              int64        `protobuf:"varint,10,opt,name=roundID,proto3" json:"roundID,omitempty"`
	Init                 string       `protobuf:"bytes,11,opt,name=init,proto3" json:"init,omitempty"`
	Log                  []*RecordLog `protobuf:"bytes,12,rep,name=log,proto3" json:"log,omitempty"`
	Symbol               string       `protobuf:"bytes,13,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Balance              float64      `protobuf:"fixed64,14,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceCash          float64      `protobuf:"fixed64,15,opt,name=balance_cash,json=balanceCash,proto3" json:"balance_cash,omitempty"`
	BalanceBonus         float64      `protobuf:"fixed64,16,opt,name=balance_bonus,json=balanceBonus,proto3" json:"balance_bonus,omitempty"`
	Hash                 string       `protobuf:"bytes,17,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RecordItem) Reset()         { *m = RecordItem{} }
func (m *RecordItem) String() string { return proto.CompactTextString(m) }
func (*RecordItem) ProtoMessage()    {}
func (*RecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{7}
}

func (m *RecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordItem.Unmarshal(m, b)
}
func (m *RecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordItem.Marshal(b, m, deterministic)
}
func (m *RecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordItem.Merge(m, src)
}
func (m *RecordItem) XXX_Size() int {
	return xxx_messageInfo_RecordItem.Size(m)
}
func (m *RecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_RecordItem proto.InternalMessageInfo

func (m *RecordItem) GetAgentId() uint32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *RecordItem) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RecordItem) GetBet() float64 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *RecordItem) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *RecordItem) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *RecordItem) GetBaseBet() float64 {
	if m != nil {
		return m.BaseBet
	}
	return 0
}

func (m *RecordItem) GetWin() float64 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *RecordItem) GetRtp() float64 {
	if m != nil {
		return m.Rtp
	}
	return 0
}

func (m *RecordItem) GetPlayedDate() int64 {
	if m != nil {
		return m.PlayedDate
	}
	return 0
}

func (m *RecordItem) GetRoundID() int64 {
	if m != nil {
		return m.RoundID
	}
	return 0
}

func (m *RecordItem) GetInit() string {
	if m != nil {
		return m.Init
	}
	return ""
}

func (m *RecordItem) GetLog() []*RecordLog {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *RecordItem) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RecordItem) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *RecordItem) GetBalanceCash() float64 {
	if m != nil {
		return m.BalanceCash
	}
	return 0
}

func (m *RecordItem) GetBalanceBonus() float64 {
	if m != nil {
		return m.BalanceBonus
	}
	return 0
}

func (m *RecordItem) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetRecordsResp struct {
	Code                 ErrorCode     `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	Data                 []*RecordItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetRecordsResp) Reset()         { *m = GetRecordsResp{} }
func (m *GetRecordsResp) String() string { return proto.CompactTextString(m) }
func (*GetRecordsResp) ProtoMessage()    {}
func (*GetRecordsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{8}
}

func (m *GetRecordsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsResp.Unmarshal(m, b)
}
func (m *GetRecordsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsResp.Marshal(b, m, deterministic)
}
func (m *GetRecordsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsResp.Merge(m, src)
}
func (m *GetRecordsResp) XXX_Size() int {
	return xxx_messageInfo_GetRecordsResp.Size(m)
}
func (m *GetRecordsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsResp proto.InternalMessageInfo

func (m *GetRecordsResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func (m *GetRecordsResp) GetData() []*RecordItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type RecordLog struct {
	Cr                   string   `protobuf:"bytes,1,opt,name=cr,proto3" json:"cr,omitempty"`
	Sr                   string   `protobuf:"bytes,2,opt,name=sr,proto3" json:"sr,omitempty"`
	RoundId              int64    `protobuf:"varint,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordLog) Reset()         { *m = RecordLog{} }
func (m *RecordLog) String() string { return proto.CompactTextString(m) }
func (*RecordLog) ProtoMessage()    {}
func (*RecordLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{9}
}

func (m *RecordLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordLog.Unmarshal(m, b)
}
func (m *RecordLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordLog.Marshal(b, m, deterministic)
}
func (m *RecordLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordLog.Merge(m, src)
}
func (m *RecordLog) XXX_Size() int {
	return xxx_messageInfo_RecordLog.Size(m)
}
func (m *RecordLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordLog.DiscardUnknown(m)
}

var xxx_messageInfo_RecordLog proto.InternalMessageInfo

func (m *RecordLog) GetCr() string {
	if m != nil {
		return m.Cr
	}
	return ""
}

func (m *RecordLog) GetSr() string {
	if m != nil {
		return m.Sr
	}
	return ""
}

func (m *RecordLog) GetRoundId() int64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type GetPlayerReq struct {
	PlayerId             uint32   `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Factory              uint32   `protobuf:"varint,2,opt,name=Factory,proto3" json:"Factory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerReq) Reset()         { *m = GetPlayerReq{} }
func (m *GetPlayerReq) String() string { return proto.CompactTextString(m) }
func (*GetPlayerReq) ProtoMessage()    {}
func (*GetPlayerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{10}
}

func (m *GetPlayerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerReq.Unmarshal(m, b)
}
func (m *GetPlayerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerReq.Marshal(b, m, deterministic)
}
func (m *GetPlayerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerReq.Merge(m, src)
}
func (m *GetPlayerReq) XXX_Size() int {
	return xxx_messageInfo_GetPlayerReq.Size(m)
}
func (m *GetPlayerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerReq proto.InternalMessageInfo

func (m *GetPlayerReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *GetPlayerReq) GetFactory() uint32 {
	if m != nil {
		return m.Factory
	}
	return 0
}

type GetPlayerResp struct {
	HumanPlayer          *HumanPlayer `protobuf:"bytes,1,opt,name=HumanPlayer,proto3" json:"HumanPlayer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPlayerResp) Reset()         { *m = GetPlayerResp{} }
func (m *GetPlayerResp) String() string { return proto.CompactTextString(m) }
func (*GetPlayerResp) ProtoMessage()    {}
func (*GetPlayerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{11}
}

func (m *GetPlayerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerResp.Unmarshal(m, b)
}
func (m *GetPlayerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerResp.Marshal(b, m, deterministic)
}
func (m *GetPlayerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerResp.Merge(m, src)
}
func (m *GetPlayerResp) XXX_Size() int {
	return xxx_messageInfo_GetPlayerResp.Size(m)
}
func (m *GetPlayerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerResp proto.InternalMessageInfo

func (m *GetPlayerResp) GetHumanPlayer() *HumanPlayer {
	if m != nil {
		return m.HumanPlayer
	}
	return nil
}

type GetValueReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TimeOut              int64    `protobuf:"varint,2,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueReq) Reset()         { *m = GetValueReq{} }
func (m *GetValueReq) String() string { return proto.CompactTextString(m) }
func (*GetValueReq) ProtoMessage()    {}
func (*GetValueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{12}
}

func (m *GetValueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueReq.Unmarshal(m, b)
}
func (m *GetValueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueReq.Marshal(b, m, deterministic)
}
func (m *GetValueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueReq.Merge(m, src)
}
func (m *GetValueReq) XXX_Size() int {
	return xxx_messageInfo_GetValueReq.Size(m)
}
func (m *GetValueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueReq proto.InternalMessageInfo

func (m *GetValueReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetValueReq) GetTimeOut() int64 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

type GetValueResp struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	Value                string    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetValueResp) Reset()         { *m = GetValueResp{} }
func (m *GetValueResp) String() string { return proto.CompactTextString(m) }
func (*GetValueResp) ProtoMessage()    {}
func (*GetValueResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{13}
}

func (m *GetValueResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResp.Unmarshal(m, b)
}
func (m *GetValueResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResp.Marshal(b, m, deterministic)
}
func (m *GetValueResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResp.Merge(m, src)
}
func (m *GetValueResp) XXX_Size() int {
	return xxx_messageInfo_GetValueResp.Size(m)
}
func (m *GetValueResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResp proto.InternalMessageInfo

func (m *GetValueResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func (m *GetValueResp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetValueReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeOut              int32    `protobuf:"varint,3,opt,name=time_out,json=timeOut,proto3" json:"time_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetValueReq) Reset()         { *m = SetValueReq{} }
func (m *SetValueReq) String() string { return proto.CompactTextString(m) }
func (*SetValueReq) ProtoMessage()    {}
func (*SetValueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{14}
}

func (m *SetValueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueReq.Unmarshal(m, b)
}
func (m *SetValueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueReq.Marshal(b, m, deterministic)
}
func (m *SetValueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueReq.Merge(m, src)
}
func (m *SetValueReq) XXX_Size() int {
	return xxx_messageInfo_SetValueReq.Size(m)
}
func (m *SetValueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueReq proto.InternalMessageInfo

func (m *SetValueReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetValueReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetValueReq) GetTimeOut() int32 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

type SetValueResp struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetValueResp) Reset()         { *m = SetValueResp{} }
func (m *SetValueResp) String() string { return proto.CompactTextString(m) }
func (*SetValueResp) ProtoMessage()    {}
func (*SetValueResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{15}
}

func (m *SetValueResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetValueResp.Unmarshal(m, b)
}
func (m *SetValueResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetValueResp.Marshal(b, m, deterministic)
}
func (m *SetValueResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetValueResp.Merge(m, src)
}
func (m *SetValueResp) XXX_Size() int {
	return xxx_messageInfo_SetValueResp.Size(m)
}
func (m *SetValueResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetValueResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetValueResp proto.InternalMessageInfo

func (m *SetValueResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

type UpdatePlayerAvatarAndGenderReq struct {
	PlayerId             uint32   `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender               uint32   `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Factory              uint32   `protobuf:"varint,4,opt,name=Factory,proto3" json:"Factory,omitempty"`
	HeadFrame            string   `protobuf:"bytes,5,opt,name=head_frame,json=headFrame,proto3" json:"head_frame,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerAvatarAndGenderReq) Reset()         { *m = UpdatePlayerAvatarAndGenderReq{} }
func (m *UpdatePlayerAvatarAndGenderReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerAvatarAndGenderReq) ProtoMessage()    {}
func (*UpdatePlayerAvatarAndGenderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{16}
}

func (m *UpdatePlayerAvatarAndGenderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderReq.Unmarshal(m, b)
}
func (m *UpdatePlayerAvatarAndGenderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderReq.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerAvatarAndGenderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerAvatarAndGenderReq.Merge(m, src)
}
func (m *UpdatePlayerAvatarAndGenderReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderReq.Size(m)
}
func (m *UpdatePlayerAvatarAndGenderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerAvatarAndGenderReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerAvatarAndGenderReq proto.InternalMessageInfo

func (m *UpdatePlayerAvatarAndGenderReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *UpdatePlayerAvatarAndGenderReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpdatePlayerAvatarAndGenderReq) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UpdatePlayerAvatarAndGenderReq) GetFactory() uint32 {
	if m != nil {
		return m.Factory
	}
	return 0
}

func (m *UpdatePlayerAvatarAndGenderReq) GetHeadFrame() string {
	if m != nil {
		return m.HeadFrame
	}
	return ""
}

func (m *UpdatePlayerAvatarAndGenderReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdatePlayerAvatarAndGenderResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayerAvatarAndGenderResp) Reset()         { *m = UpdatePlayerAvatarAndGenderResp{} }
func (m *UpdatePlayerAvatarAndGenderResp) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerAvatarAndGenderResp) ProtoMessage()    {}
func (*UpdatePlayerAvatarAndGenderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3733bc645feed7a, []int{17}
}

func (m *UpdatePlayerAvatarAndGenderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderResp.Unmarshal(m, b)
}
func (m *UpdatePlayerAvatarAndGenderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderResp.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerAvatarAndGenderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerAvatarAndGenderResp.Merge(m, src)
}
func (m *UpdatePlayerAvatarAndGenderResp) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerAvatarAndGenderResp.Size(m)
}
func (m *UpdatePlayerAvatarAndGenderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerAvatarAndGenderResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerAvatarAndGenderResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetGameListReq)(nil), "services.GetGameListReq")
	proto.RegisterType((*GetGameListResp)(nil), "services.GetGameListResp")
	proto.RegisterType((*GetGameListResp_GameInfoItem)(nil), "services.GetGameListResp.GameInfoItem")
	proto.RegisterType((*UserLockReq)(nil), "services.UserLockReq")
	proto.RegisterType((*UserLockResp)(nil), "services.UserLockResp")
	proto.RegisterType((*UserUnLockReq)(nil), "services.UserUnLockReq")
	proto.RegisterType((*UserUnLockResp)(nil), "services.UserUnLockResp")
	proto.RegisterType((*GetRecordsReq)(nil), "services.GetRecordsReq")
	proto.RegisterType((*RecordItem)(nil), "services.RecordItem")
	proto.RegisterType((*GetRecordsResp)(nil), "services.GetRecordsResp")
	proto.RegisterType((*RecordLog)(nil), "services.RecordLog")
	proto.RegisterType((*GetPlayerReq)(nil), "services.GetPlayerReq")
	proto.RegisterType((*GetPlayerResp)(nil), "services.GetPlayerResp")
	proto.RegisterType((*GetValueReq)(nil), "services.GetValueReq")
	proto.RegisterType((*GetValueResp)(nil), "services.GetValueResp")
	proto.RegisterType((*SetValueReq)(nil), "services.SetValueReq")
	proto.RegisterType((*SetValueResp)(nil), "services.SetValueResp")
	proto.RegisterType((*UpdatePlayerAvatarAndGenderReq)(nil), "services.UpdatePlayerAvatarAndGenderReq")
	proto.RegisterType((*UpdatePlayerAvatarAndGenderResp)(nil), "services.UpdatePlayerAvatarAndGenderResp")
}

func init() { proto.RegisterFile("datacenter.proto", fileDescriptor_f3733bc645feed7a) }

var fileDescriptor_f3733bc645feed7a = []byte{
	// 967 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0x1b, 0x37,
	0x10, 0x86, 0xb4, 0x92, 0x2d, 0x8d, 0x7e, 0xa2, 0xb0, 0x8e, 0xcb, 0x6c, 0xdb, 0xd4, 0xd9, 0x22,
	0x86, 0x7a, 0xf1, 0xc1, 0x3d, 0x34, 0x01, 0x52, 0x04, 0x71, 0xdc, 0xc8, 0x06, 0x8c, 0x36, 0x58,
	0xc1, 0xbd, 0x1a, 0xd4, 0xee, 0xc4, 0x16, 0x2c, 0x71, 0xd7, 0x24, 0x65, 0x43, 0x8f, 0x56, 0xa0,
	0xcf, 0xd1, 0x37, 0xe9, 0xbd, 0x18, 0x72, 0x7f, 0x53, 0xc5, 0x69, 0x72, 0xe3, 0xf7, 0x71, 0x66,
	0xf8, 0x71, 0x38, 0xb3, 0xb3, 0x30, 0x8a, 0x85, 0x11, 0x11, 0x4a, 0x83, 0xea, 0x20, 0x55, 0x89,
	0x49, 0x58, 0x47, 0xa3, 0xba, 0x9d, 0x47, 0xa8, 0xfd, 0x7e, 0xba, 0x10, 0xeb, 0x9c, 0xf7, 0x61,
	0x26, 0x34, 0xba, 0x75, 0x30, 0x82, 0xe1, 0x04, 0xcd, 0x44, 0x2c, 0xf1, 0x6c, 0xae, 0x4d, 0x88,
	0x37, 0xc1, 0x3f, 0x0d, 0x78, 0x50, 0xa3, 0x74, 0xca, 0xc6, 0xd0, 0x8a, 0x92, 0x18, 0x79, 0x63,
	0xaf, 0x31, 0x1e, 0x1e, 0xee, 0x1c, 0xe4, 0x81, 0x0f, 0x50, 0xa9, 0x44, 0x5d, 0xd0, 0x5e, 0x68,
	0x2d, 0xd8, 0x08, 0xbc, 0xab, 0xc4, 0xf0, 0xe6, 0x9e, 0x37, 0xee, 0x86, 0xb4, 0x24, 0x46, 0xe2,
	0x1d, 0xf7, 0x1c, 0x23, 0xf1, 0x8e, 0x7d, 0x0b, 0x5d, 0x85, 0x51, 0xb2, 0x5c, 0xa2, 0x8c, 0x79,
	0xcb, 0xf2, 0x25, 0xc1, 0x9e, 0x83, 0x27, 0x16, 0x0b, 0xde, 0xde, 0xf3, 0xc6, 0xbd, 0xc3, 0xfd,
	0xf2, 0xa8, 0x0f, 0x34, 0x1d, 0x10, 0x38, 0x95, 0xef, 0x93, 0x53, 0x83, 0xcb, 0x90, 0x5c, 0xfc,
	0x97, 0xd0, 0xaf, 0x92, 0x6c, 0x17, 0xb6, 0xf4, 0x7a, 0x39, 0x4b, 0x16, 0x56, 0x77, 0x37, 0xcc,
	0x10, 0xdb, 0x81, 0xb6, 0x36, 0xc2, 0x20, 0x6f, 0xee, 0x35, 0xc6, 0xed, 0xd0, 0x81, 0xe0, 0x19,
	0xf4, 0xce, 0x35, 0xaa, 0xb3, 0x24, 0xba, 0x0e, 0xf1, 0x86, 0x9c, 0x57, 0x1a, 0xd5, 0x69, 0x6c,
	0x9d, 0x07, 0x61, 0x86, 0x82, 0x7d, 0xe8, 0x97, 0x66, 0x3a, 0x25, 0x3b, 0x85, 0x7a, 0xb5, 0x30,
	0xf9, 0x21, 0x0e, 0x05, 0xbf, 0xc0, 0x80, 0xec, 0xce, 0xe5, 0x27, 0x02, 0x92, 0x1a, 0x93, 0x5c,
	0xa3, 0xb4, 0x6a, 0xba, 0xa1, 0x03, 0xc1, 0x18, 0x86, 0x55, 0xf7, 0xff, 0x1c, 0xd4, 0x29, 0x0e,
	0x9a, 0xc2, 0x60, 0x82, 0x26, 0xc4, 0x28, 0x51, 0xb1, 0xce, 0x0e, 0x3a, 0x2f, 0x0f, 0xf2, 0xc2,
	0x0c, 0x11, 0x3f, 0x75, 0xe9, 0x70, 0x27, 0x65, 0x88, 0x31, 0x68, 0x9d, 0x08, 0x7d, 0xc5, 0x3d,
	0xcb, 0xda, 0x75, 0xf0, 0xb7, 0x07, 0xe0, 0x42, 0xda, 0x4c, 0x72, 0xd8, 0x16, 0x97, 0x28, 0x4d,
	0x21, 0x3e, 0x87, 0x95, 0x5b, 0x35, 0x6b, 0xb7, 0x1a, 0x81, 0x37, 0x43, 0x63, 0x63, 0x36, 0x42,
	0x5a, 0x32, 0x1f, 0x3a, 0xd1, 0x4a, 0x29, 0x94, 0xd1, 0x9a, 0xb7, 0xec, 0x51, 0x05, 0x66, 0xfb,
	0x30, 0xcc, 0xd7, 0x99, 0xc4, 0xb6, 0xb5, 0xf8, 0x80, 0x65, 0x8f, 0xa1, 0x43, 0xb5, 0x7b, 0x41,
	0xa1, 0xb7, 0x6c, 0xe8, 0x6d, 0xc2, 0x47, 0x68, 0xcb, 0xec, 0x6e, 0x2e, 0xf9, 0xb6, 0x3b, 0xf0,
	0x6e, 0x2e, 0x89, 0x51, 0x26, 0xe5, 0x1d, 0xc7, 0x28, 0x93, 0xb2, 0x27, 0x00, 0xb6, 0x11, 0xe2,
	0x63, 0x7a, 0xfd, 0xae, 0xcd, 0x4e, 0x85, 0xa1, 0x6b, 0xaa, 0x64, 0x25, 0xe3, 0xd3, 0x63, 0x0e,
	0x76, 0x33, 0x87, 0x94, 0xa3, 0xb9, 0x9c, 0x1b, 0xde, 0x73, 0x39, 0xa2, 0x35, 0x7b, 0x06, 0xde,
	0x22, 0xb9, 0xe4, 0x7d, 0x5b, 0xa8, 0x5f, 0x95, 0x85, 0xea, 0xf2, 0x76, 0x96, 0x5c, 0x86, 0xb4,
	0x5f, 0xa9, 0xc2, 0x41, 0xad, 0x0a, 0x39, 0x6c, 0xcf, 0xc4, 0x42, 0xc8, 0x08, 0xf9, 0x30, 0xbf,
	0x8a, 0x85, 0xec, 0x29, 0xf4, 0xb3, 0xe5, 0x45, 0x44, 0x0f, 0xf3, 0xc0, 0x6e, 0xf7, 0x32, 0xee,
	0x8d, 0xd0, 0x57, 0xec, 0x07, 0x18, 0xe4, 0x26, 0xb3, 0x44, 0xae, 0x34, 0x1f, 0x59, 0x9b, 0xdc,
	0xef, 0x88, 0x38, 0x12, 0x7d, 0x45, 0xfe, 0x0f, 0x9d, 0x68, 0x5a, 0x07, 0xb1, 0xed, 0xf7, 0xa2,
	0x5a, 0x3e, 0xab, 0xb7, 0xc7, 0xd0, 0xa2, 0x6f, 0x8c, 0x6d, 0xee, 0x5e, 0xd5, 0xb2, 0xac, 0x94,
	0xd0, 0x5a, 0x04, 0xbf, 0x42, 0xb7, 0xc8, 0x02, 0x1b, 0x42, 0x33, 0x52, 0x59, 0x77, 0x34, 0x23,
	0x45, 0x58, 0xab, 0xac, 0x06, 0x9b, 0x5a, 0x95, 0x59, 0x8f, 0x6d, 0xb9, 0x14, 0x59, 0x8f, 0x83,
	0x63, 0xe8, 0x4f, 0xd0, 0xbc, 0xb3, 0xdf, 0x2e, 0xaa, 0x6c, 0x1f, 0x3a, 0x0e, 0x14, 0x75, 0x58,
	0x60, 0x8a, 0xf2, 0x56, 0x44, 0x26, 0x51, 0xeb, 0xac, 0x12, 0x73, 0x18, 0x9c, 0xd8, 0x06, 0xc9,
	0xa3, 0xe8, 0x94, 0xfd, 0x0c, 0xbd, 0x93, 0xd5, 0x52, 0x48, 0x47, 0xd9, 0x48, 0xbd, 0xc3, 0x47,
	0xe5, 0x75, 0x2a, 0x9b, 0x61, 0xd5, 0x32, 0x78, 0x01, 0xbd, 0x09, 0x9a, 0x3f, 0xc4, 0x62, 0x85,
	0x24, 0x67, 0x04, 0xde, 0x35, 0xae, 0xb3, 0x9b, 0xd1, 0x92, 0x44, 0x98, 0xf9, 0x12, 0x7f, 0x5f,
	0x19, 0x2b, 0xc2, 0x0b, 0x73, 0x18, 0xfc, 0x66, 0xaf, 0x92, 0xb9, 0x7e, 0x56, 0xd6, 0x77, 0xa0,
	0x7d, 0x4b, 0x6e, 0xf9, 0xf7, 0xc1, 0x82, 0xe0, 0x1d, 0xf4, 0xa6, 0xf7, 0x4a, 0xd9, 0xe8, 0x46,
	0x0d, 0x44, 0x8a, 0x2e, 0x92, 0x95, 0xeb, 0xcd, 0x76, 0xa9, 0xf0, 0x39, 0xf4, 0xa7, 0x5f, 0xa4,
	0x30, 0xf8, 0xb3, 0x01, 0x4f, 0xce, 0xd3, 0x58, 0x18, 0x74, 0x79, 0x7a, 0x7d, 0x2b, 0x8c, 0x50,
	0xaf, 0x65, 0x3c, 0x41, 0x19, 0x7f, 0xfa, 0xe5, 0x76, 0x61, 0xcb, 0x79, 0xe4, 0xdf, 0x25, 0x87,
	0x88, 0x77, 0x01, 0xac, 0xd2, 0x41, 0x98, 0xa1, 0xea, 0x4b, 0xb7, 0x6a, 0x2f, 0xcd, 0xbe, 0x03,
	0xb8, 0x42, 0x11, 0x5f, 0xbc, 0x57, 0x62, 0x89, 0xd9, 0x27, 0xa4, 0x4b, 0xcc, 0x5b, 0x22, 0xa8,
	0x1f, 0x24, 0x6d, 0x6c, 0xb9, 0x7e, 0xa0, 0x75, 0xf0, 0x14, 0xbe, 0xbf, 0x57, 0xba, 0x4e, 0x0f,
	0xff, 0x6a, 0xc1, 0xc3, 0x63, 0x61, 0xc4, 0x1b, 0x3b, 0x5b, 0xa7, 0x2e, 0x0d, 0xec, 0x25, 0x74,
	0x8b, 0xaa, 0x62, 0xbb, 0xb5, 0x31, 0x55, 0x14, 0xac, 0xff, 0xf5, 0x46, 0x5e, 0xa7, 0xec, 0x05,
	0x74, 0xf2, 0x72, 0x60, 0x8f, 0x6a, 0x46, 0xf9, 0x93, 0xfa, 0xbb, 0x9b, 0x68, 0xe7, 0x3a, 0xdd,
	0xe0, 0x3a, 0xdd, 0xec, 0x5a, 0x7b, 0x52, 0x05, 0xdf, 0xdc, 0x73, 0x59, 0x36, 0x2e, 0xdd, 0xee,
	0x7f, 0x4e, 0xff, 0xc7, 0xff, 0x69, 0xa9, 0x53, 0xf6, 0x0a, 0xa0, 0xfc, 0xe0, 0xb0, 0x7a, 0x42,
	0xca, 0xa1, 0xe5, 0xf3, 0xcd, 0x1b, 0x3a, 0x65, 0x47, 0xb6, 0xe9, 0xf2, 0xd1, 0xcf, 0xf8, 0x47,
	0xfe, 0x08, 0x6e, 0xfc, 0xc7, 0x1f, 0xfd, 0x57, 0xa0, 0x9c, 0xe5, 0x43, 0xbb, 0x9a, 0xb3, 0xca,
	0xbc, 0xaf, 0xe6, 0xac, 0x36, 0xdf, 0x5f, 0x01, 0x94, 0x83, 0xb8, 0xaa, 0xbf, 0x36, 0xdd, 0xab,
	0xfa, 0xeb, 0x73, 0x7b, 0xb6, 0x65, 0x7f, 0xb4, 0x7e, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x07,
	0x10, 0xae, 0x0a, 0xa0, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataCenterServiceClient is the client API for DataCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataCenterServiceClient interface {
	// 获取玩家信息
	GetPlayer(ctx context.Context, in *GetPlayerReq, opts ...grpc.CallOption) (*GetPlayerResp, error)
	// 获取指定键值
	GetValue(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResp, error)
	// 缓存
	SetValue(ctx context.Context, in *SetValueReq, opts ...grpc.CallOption) (*SetValueResp, error)
	// 修改玩家信息
	UpdatePlayerAvatarAndGender(ctx context.Context, in *UpdatePlayerAvatarAndGenderReq, opts ...grpc.CallOption) (*UpdatePlayerAvatarAndGenderResp, error)
	// 获取注单信息
	GetRecords(ctx context.Context, in *GetRecordsReq, opts ...grpc.CallOption) (*GetRecordsResp, error)
	// 获取游戏列表
	GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error)
	// 加锁
	UserLock(ctx context.Context, in *UserLockReq, opts ...grpc.CallOption) (*UserLockResp, error)
	// 解锁
	UserUnLock(ctx context.Context, in *UserUnLockReq, opts ...grpc.CallOption) (*UserUnLockResp, error)
}

type dataCenterServiceClient struct {
	cc *grpc.ClientConn
}

func NewDataCenterServiceClient(cc *grpc.ClientConn) DataCenterServiceClient {
	return &dataCenterServiceClient{cc}
}

func (c *dataCenterServiceClient) GetPlayer(ctx context.Context, in *GetPlayerReq, opts ...grpc.CallOption) (*GetPlayerResp, error) {
	out := new(GetPlayerResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/GetPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetValue(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResp, error) {
	out := new(GetValueResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) SetValue(ctx context.Context, in *SetValueReq, opts ...grpc.CallOption) (*SetValueResp, error) {
	out := new(SetValueResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UpdatePlayerAvatarAndGender(ctx context.Context, in *UpdatePlayerAvatarAndGenderReq, opts ...grpc.CallOption) (*UpdatePlayerAvatarAndGenderResp, error) {
	out := new(UpdatePlayerAvatarAndGenderResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/UpdatePlayerAvatarAndGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetRecords(ctx context.Context, in *GetRecordsReq, opts ...grpc.CallOption) (*GetRecordsResp, error) {
	out := new(GetRecordsResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/GetRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) GetGameList(ctx context.Context, in *GetGameListReq, opts ...grpc.CallOption) (*GetGameListResp, error) {
	out := new(GetGameListResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/GetGameList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UserLock(ctx context.Context, in *UserLockReq, opts ...grpc.CallOption) (*UserLockResp, error) {
	out := new(UserLockResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/UserLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterServiceClient) UserUnLock(ctx context.Context, in *UserUnLockReq, opts ...grpc.CallOption) (*UserUnLockResp, error) {
	out := new(UserUnLockResp)
	err := c.cc.Invoke(ctx, "/services.DataCenterService/UserUnLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCenterServiceServer is the server API for DataCenterService service.
type DataCenterServiceServer interface {
	// 获取玩家信息
	GetPlayer(context.Context, *GetPlayerReq) (*GetPlayerResp, error)
	// 获取指定键值
	GetValue(context.Context, *GetValueReq) (*GetValueResp, error)
	// 缓存
	SetValue(context.Context, *SetValueReq) (*SetValueResp, error)
	// 修改玩家信息
	UpdatePlayerAvatarAndGender(context.Context, *UpdatePlayerAvatarAndGenderReq) (*UpdatePlayerAvatarAndGenderResp, error)
	// 获取注单信息
	GetRecords(context.Context, *GetRecordsReq) (*GetRecordsResp, error)
	// 获取游戏列表
	GetGameList(context.Context, *GetGameListReq) (*GetGameListResp, error)
	// 加锁
	UserLock(context.Context, *UserLockReq) (*UserLockResp, error)
	// 解锁
	UserUnLock(context.Context, *UserUnLockReq) (*UserUnLockResp, error)
}

// UnimplementedDataCenterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataCenterServiceServer struct {
}

func (*UnimplementedDataCenterServiceServer) GetPlayer(ctx context.Context, req *GetPlayerReq) (*GetPlayerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayer not implemented")
}
func (*UnimplementedDataCenterServiceServer) GetValue(ctx context.Context, req *GetValueReq) (*GetValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (*UnimplementedDataCenterServiceServer) SetValue(ctx context.Context, req *SetValueReq) (*SetValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (*UnimplementedDataCenterServiceServer) UpdatePlayerAvatarAndGender(ctx context.Context, req *UpdatePlayerAvatarAndGenderReq) (*UpdatePlayerAvatarAndGenderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlayerAvatarAndGender not implemented")
}
func (*UnimplementedDataCenterServiceServer) GetRecords(ctx context.Context, req *GetRecordsReq) (*GetRecordsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecords not implemented")
}
func (*UnimplementedDataCenterServiceServer) GetGameList(ctx context.Context, req *GetGameListReq) (*GetGameListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameList not implemented")
}
func (*UnimplementedDataCenterServiceServer) UserLock(ctx context.Context, req *UserLockReq) (*UserLockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLock not implemented")
}
func (*UnimplementedDataCenterServiceServer) UserUnLock(ctx context.Context, req *UserUnLockReq) (*UserUnLockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUnLock not implemented")
}

func RegisterDataCenterServiceServer(s *grpc.Server, srv DataCenterServiceServer) {
	s.RegisterService(&_DataCenterService_serviceDesc, srv)
}

func _DataCenterService_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/GetPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetPlayer(ctx, req.(*GetPlayerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetValue(ctx, req.(*GetValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).SetValue(ctx, req.(*SetValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UpdatePlayerAvatarAndGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerAvatarAndGenderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UpdatePlayerAvatarAndGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/UpdatePlayerAvatarAndGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UpdatePlayerAvatarAndGender(ctx, req.(*UpdatePlayerAvatarAndGenderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/GetRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetRecords(ctx, req.(*GetRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_GetGameList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).GetGameList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/GetGameList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).GetGameList(ctx, req.(*GetGameListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UserLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UserLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/UserLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UserLock(ctx, req.(*UserLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenterService_UserUnLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUnLockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServiceServer).UserUnLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.DataCenterService/UserUnLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServiceServer).UserUnLock(ctx, req.(*UserUnLockReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataCenterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.DataCenterService",
	HandlerType: (*DataCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlayer",
			Handler:    _DataCenterService_GetPlayer_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _DataCenterService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _DataCenterService_SetValue_Handler,
		},
		{
			MethodName: "UpdatePlayerAvatarAndGender",
			Handler:    _DataCenterService_UpdatePlayerAvatarAndGender_Handler,
		},
		{
			MethodName: "GetRecords",
			Handler:    _DataCenterService_GetRecords_Handler,
		},
		{
			MethodName: "GetGameList",
			Handler:    _DataCenterService_GetGameList_Handler,
		},
		{
			MethodName: "UserLock",
			Handler:    _DataCenterService_UserLock_Handler,
		},
		{
			MethodName: "UserUnLock",
			Handler:    _DataCenterService_UserUnLock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datacenter.proto",
}
