// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lottery.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGameStateReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameStateReq) Reset()         { *m = GetGameStateReq{} }
func (m *GetGameStateReq) String() string { return proto.CompactTextString(m) }
func (*GetGameStateReq) ProtoMessage()    {}
func (*GetGameStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{0}
}

func (m *GetGameStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameStateReq.Unmarshal(m, b)
}
func (m *GetGameStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameStateReq.Marshal(b, m, deterministic)
}
func (m *GetGameStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameStateReq.Merge(m, src)
}
func (m *GetGameStateReq) XXX_Size() int {
	return xxx_messageInfo_GetGameStateReq.Size(m)
}
func (m *GetGameStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameStateReq proto.InternalMessageInfo

func (m *GetGameStateReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetGameStateReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type GetGameStateResp struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	Data                 string    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetGameStateResp) Reset()         { *m = GetGameStateResp{} }
func (m *GetGameStateResp) String() string { return proto.CompactTextString(m) }
func (*GetGameStateResp) ProtoMessage()    {}
func (*GetGameStateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{1}
}

func (m *GetGameStateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameStateResp.Unmarshal(m, b)
}
func (m *GetGameStateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameStateResp.Marshal(b, m, deterministic)
}
func (m *GetGameStateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameStateResp.Merge(m, src)
}
func (m *GetGameStateResp) XXX_Size() int {
	return xxx_messageInfo_GetGameStateResp.Size(m)
}
func (m *GetGameStateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameStateResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameStateResp proto.InternalMessageInfo

func (m *GetGameStateResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func (m *GetGameStateResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SaveGameStateReq struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveGameStateReq) Reset()         { *m = SaveGameStateReq{} }
func (m *SaveGameStateReq) String() string { return proto.CompactTextString(m) }
func (*SaveGameStateReq) ProtoMessage()    {}
func (*SaveGameStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{2}
}

func (m *SaveGameStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveGameStateReq.Unmarshal(m, b)
}
func (m *SaveGameStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveGameStateReq.Marshal(b, m, deterministic)
}
func (m *SaveGameStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveGameStateReq.Merge(m, src)
}
func (m *SaveGameStateReq) XXX_Size() int {
	return xxx_messageInfo_SaveGameStateReq.Size(m)
}
func (m *SaveGameStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveGameStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveGameStateReq proto.InternalMessageInfo

func (m *SaveGameStateReq) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SaveGameStateReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SaveGameStateReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SaveGameStateResp struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveGameStateResp) Reset()         { *m = SaveGameStateResp{} }
func (m *SaveGameStateResp) String() string { return proto.CompactTextString(m) }
func (*SaveGameStateResp) ProtoMessage()    {}
func (*SaveGameStateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{3}
}

func (m *SaveGameStateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveGameStateResp.Unmarshal(m, b)
}
func (m *SaveGameStateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveGameStateResp.Marshal(b, m, deterministic)
}
func (m *SaveGameStateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveGameStateResp.Merge(m, src)
}
func (m *SaveGameStateResp) XXX_Size() int {
	return xxx_messageInfo_SaveGameStateResp.Size(m)
}
func (m *SaveGameStateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveGameStateResp.DiscardUnknown(m)
}

var xxx_messageInfo_SaveGameStateResp proto.InternalMessageInfo

func (m *SaveGameStateResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

type LotteryReq struct {
	PlayerId             uint32   `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	CurrencyType         string   `protobuf:"bytes,5,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	AgentId              int64    `protobuf:"varint,6,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Symbol               string   `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ProfitLoss           string   `protobuf:"bytes,8,opt,name=profitLoss,proto3" json:"profitLoss,omitempty"`
	Bet                  string   `protobuf:"bytes,9,opt,name=bet,proto3" json:"bet,omitempty"`
	State                string   `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Action               string   `protobuf:"bytes,11,opt,name=action,proto3" json:"action,omitempty"`
	RoundID              int64    `protobuf:"varint,12,opt,name=roundID,proto3" json:"roundID,omitempty"`
	MaxProfitLoss        string   `protobuf:"bytes,13,opt,name=maxProfitLoss,proto3" json:"maxProfitLoss,omitempty"`
	Complete             bool     `protobuf:"varint,14,opt,name=complete,proto3" json:"complete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LotteryReq) Reset()         { *m = LotteryReq{} }
func (m *LotteryReq) String() string { return proto.CompactTextString(m) }
func (*LotteryReq) ProtoMessage()    {}
func (*LotteryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{4}
}

func (m *LotteryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryReq.Unmarshal(m, b)
}
func (m *LotteryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryReq.Marshal(b, m, deterministic)
}
func (m *LotteryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryReq.Merge(m, src)
}
func (m *LotteryReq) XXX_Size() int {
	return xxx_messageInfo_LotteryReq.Size(m)
}
func (m *LotteryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryReq.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryReq proto.InternalMessageInfo

func (m *LotteryReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LotteryReq) GetCurrencyType() string {
	if m != nil {
		return m.CurrencyType
	}
	return ""
}

func (m *LotteryReq) GetAgentId() int64 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *LotteryReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *LotteryReq) GetProfitLoss() string {
	if m != nil {
		return m.ProfitLoss
	}
	return ""
}

func (m *LotteryReq) GetBet() string {
	if m != nil {
		return m.Bet
	}
	return ""
}

func (m *LotteryReq) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LotteryReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *LotteryReq) GetRoundID() int64 {
	if m != nil {
		return m.RoundID
	}
	return 0
}

func (m *LotteryReq) GetMaxProfitLoss() string {
	if m != nil {
		return m.MaxProfitLoss
	}
	return ""
}

func (m *LotteryReq) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

type LotteryResp struct {
	// 玩家最新的金币数
	NewCurrency string `protobuf:"bytes,1,opt,name=newCurrency,proto3" json:"newCurrency,omitempty"`
	Result      bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	// 当前可赔付值
	Pay                  string    `protobuf:"bytes,3,opt,name=pay,proto3" json:"pay,omitempty"`
	Code                 ErrorCode `protobuf:"varint,4,opt,name=code,proto3,enum=services.ErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LotteryResp) Reset()         { *m = LotteryResp{} }
func (m *LotteryResp) String() string { return proto.CompactTextString(m) }
func (*LotteryResp) ProtoMessage()    {}
func (*LotteryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cce7afd61783b10, []int{5}
}

func (m *LotteryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryResp.Unmarshal(m, b)
}
func (m *LotteryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryResp.Marshal(b, m, deterministic)
}
func (m *LotteryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryResp.Merge(m, src)
}
func (m *LotteryResp) XXX_Size() int {
	return xxx_messageInfo_LotteryResp.Size(m)
}
func (m *LotteryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryResp.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryResp proto.InternalMessageInfo

func (m *LotteryResp) GetNewCurrency() string {
	if m != nil {
		return m.NewCurrency
	}
	return ""
}

func (m *LotteryResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *LotteryResp) GetPay() string {
	if m != nil {
		return m.Pay
	}
	return ""
}

func (m *LotteryResp) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_OK
}

func init() {
	proto.RegisterType((*GetGameStateReq)(nil), "services.GetGameStateReq")
	proto.RegisterType((*GetGameStateResp)(nil), "services.GetGameStateResp")
	proto.RegisterType((*SaveGameStateReq)(nil), "services.SaveGameStateReq")
	proto.RegisterType((*SaveGameStateResp)(nil), "services.SaveGameStateResp")
	proto.RegisterType((*LotteryReq)(nil), "services.LotteryReq")
	proto.RegisterType((*LotteryResp)(nil), "services.LotteryResp")
}

func init() { proto.RegisterFile("lottery.proto", fileDescriptor_2cce7afd61783b10) }

var fileDescriptor_2cce7afd61783b10 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xb6, 0xdd, 0x36, 0x9d, 0x7e, 0x50, 0xac, 0x05, 0x99, 0x1c, 0x50, 0x14, 0x71, 0xc8,
	0xa9, 0x87, 0x45, 0xe2, 0xc6, 0x01, 0x01, 0x5a, 0x55, 0xda, 0xc3, 0xca, 0x45, 0x5c, 0x91, 0x93,
	0x0c, 0xa8, 0x52, 0x12, 0x1b, 0xdb, 0x59, 0xc8, 0x99, 0x1f, 0xc0, 0xff, 0xe1, 0xd7, 0x21, 0x3b,
	0xde, 0x34, 0x59, 0x81, 0x10, 0xda, 0xdb, 0xbc, 0x37, 0xe3, 0xe7, 0x37, 0x33, 0x36, 0xac, 0x4b,
	0x61, 0x0c, 0xaa, 0x76, 0x27, 0x95, 0x30, 0x82, 0x84, 0x1a, 0xd5, 0xed, 0x31, 0x47, 0x1d, 0x41,
	0xc6, 0x35, 0x76, 0x6c, 0xf2, 0x06, 0x1e, 0x5d, 0xa1, 0xb9, 0xe2, 0x15, 0x1e, 0x0c, 0x37, 0xc8,
	0xf0, 0x2b, 0x79, 0x0a, 0xb3, 0x46, 0xa3, 0xda, 0x17, 0x34, 0x88, 0x83, 0x74, 0xcd, 0x3c, 0xb2,
	0xbc, 0x6e, 0xab, 0x4c, 0x94, 0xf4, 0x2c, 0x0e, 0xd2, 0x05, 0xf3, 0x28, 0xb9, 0x81, 0xed, 0x58,
	0x42, 0x4b, 0x92, 0xc2, 0x34, 0x17, 0x05, 0x3a, 0x85, 0xcd, 0xe5, 0xc5, 0xee, 0xee, 0xee, 0x1d,
	0x2a, 0x25, 0xd4, 0x27, 0x9b, 0x63, 0xae, 0x82, 0x10, 0x98, 0x16, 0xdc, 0x70, 0xaf, 0xe9, 0xe2,
	0xe4, 0x23, 0x6c, 0x0f, 0xfc, 0x16, 0x1f, 0xe2, 0xaa, 0xd7, 0x9d, 0x0c, 0x74, 0x5f, 0xc3, 0xe3,
	0x7b, 0xba, 0xff, 0x63, 0x35, 0xf9, 0x75, 0x06, 0x70, 0xdd, 0xcd, 0xd4, 0x3a, 0x8a, 0x20, 0x94,
	0x25, 0x6f, 0x07, 0x9e, 0x7a, 0x4c, 0x12, 0x58, 0xe5, 0x8d, 0x52, 0x58, 0xe7, 0xed, 0x87, 0x56,
	0x22, 0x3d, 0x77, 0x2e, 0x46, 0x1c, 0xa1, 0x30, 0xe7, 0x5f, 0xb0, 0x36, 0xfb, 0x82, 0xce, 0xe2,
	0x20, 0x9d, 0xb0, 0x3b, 0x38, 0xe8, 0x69, 0x3e, 0xea, 0xe9, 0x39, 0x80, 0x54, 0xe2, 0xf3, 0xd1,
	0x5c, 0x0b, 0xad, 0x69, 0xe8, 0x72, 0x03, 0x86, 0x6c, 0x61, 0x92, 0xa1, 0xa1, 0x0b, 0x97, 0xb0,
	0x21, 0xb9, 0x80, 0x73, 0x6d, 0x3b, 0xa5, 0xe0, 0xb8, 0x0e, 0x58, 0x7d, 0x9e, 0x9b, 0xa3, 0xa8,
	0xe9, 0xb2, 0xd3, 0xef, 0x90, 0x75, 0xa4, 0x44, 0x53, 0x17, 0xfb, 0x77, 0x74, 0xd5, 0x39, 0xf2,
	0x90, 0xbc, 0x80, 0x75, 0xc5, 0xbf, 0xdf, 0x9c, 0x2e, 0x5f, 0xbb, 0x83, 0x63, 0xd2, 0x4e, 0x24,
	0x17, 0x95, 0x2c, 0xd1, 0x20, 0xdd, 0xc4, 0x41, 0x1a, 0xb2, 0x1e, 0x27, 0x3f, 0x02, 0x58, 0xf6,
	0xc3, 0xd3, 0x92, 0xc4, 0xb0, 0xac, 0xf1, 0xdb, 0x5b, 0x3f, 0x10, 0x37, 0xc0, 0x05, 0x1b, 0x52,
	0xd6, 0xa5, 0x42, 0xdd, 0x94, 0xc6, 0x6d, 0x36, 0x64, 0x1e, 0xd9, 0x2e, 0x25, 0x6f, 0xfd, 0x62,
	0x6d, 0xd8, 0xaf, 0x70, 0xfa, 0xaf, 0x15, 0x5e, 0xfe, 0x0c, 0x60, 0xe3, 0x5d, 0x1c, 0xba, 0x22,
	0xf2, 0x0a, 0xe6, 0x9e, 0x21, 0x83, 0x93, 0xa7, 0x3d, 0x47, 0x4f, 0xfe, 0xc0, 0x6a, 0x49, 0xde,
	0xc3, 0x6a, 0xf8, 0xec, 0xc9, 0xb3, 0x53, 0xd9, 0xbd, 0x1f, 0x15, 0x45, 0x7f, 0x4b, 0x69, 0x99,
	0xcd, 0xdc, 0x3f, 0x7c, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x29, 0x40, 0x53, 0xae, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LotteryServiceClient interface {
	// Lottery
	Lottery(ctx context.Context, in *LotteryReq, opts ...grpc.CallOption) (*LotteryResp, error)
	// 获取游戏记录
	GetGameState(ctx context.Context, in *GetGameStateReq, opts ...grpc.CallOption) (*GetGameStateResp, error)
}

type lotteryServiceClient struct {
	cc *grpc.ClientConn
}

func NewLotteryServiceClient(cc *grpc.ClientConn) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) Lottery(ctx context.Context, in *LotteryReq, opts ...grpc.CallOption) (*LotteryResp, error) {
	out := new(LotteryResp)
	err := c.cc.Invoke(ctx, "/services.LotteryService/Lottery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetGameState(ctx context.Context, in *GetGameStateReq, opts ...grpc.CallOption) (*GetGameStateResp, error) {
	out := new(GetGameStateResp)
	err := c.cc.Invoke(ctx, "/services.LotteryService/GetGameState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
type LotteryServiceServer interface {
	// Lottery
	Lottery(context.Context, *LotteryReq) (*LotteryResp, error)
	// 获取游戏记录
	GetGameState(context.Context, *GetGameStateReq) (*GetGameStateResp, error)
}

// UnimplementedLotteryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLotteryServiceServer struct {
}

func (*UnimplementedLotteryServiceServer) Lottery(ctx context.Context, req *LotteryReq) (*LotteryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lottery not implemented")
}
func (*UnimplementedLotteryServiceServer) GetGameState(ctx context.Context, req *GetGameStateReq) (*GetGameStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameState not implemented")
}

func RegisterLotteryServiceServer(s *grpc.Server, srv LotteryServiceServer) {
	s.RegisterService(&_LotteryService_serviceDesc, srv)
}

func _LotteryService_Lottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Lottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.LotteryService/Lottery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Lottery(ctx, req.(*LotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.LotteryService/GetGameState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetGameState(ctx, req.(*GetGameStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LotteryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lottery",
			Handler:    _LotteryService_Lottery_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _LotteryService_GetGameState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
