// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: lottery.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotteryService_Lottery_FullMethodName      = "/lottery.LotteryService/Lottery"
	LotteryService_GetGameState_FullMethodName = "/lottery.LotteryService/GetGameState"
)

// LotteryServiceClient is the client API for LotteryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotteryServiceClient interface {
	// Lottery
	Lottery(ctx context.Context, in *LotteryReq, opts ...grpc.CallOption) (*LotteryResp, error)
	// 获取游戏记录
	GetGameState(ctx context.Context, in *GetGameStateReq, opts ...grpc.CallOption) (*GetGameStateResp, error)
}

type lotteryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotteryServiceClient(cc grpc.ClientConnInterface) LotteryServiceClient {
	return &lotteryServiceClient{cc}
}

func (c *lotteryServiceClient) Lottery(ctx context.Context, in *LotteryReq, opts ...grpc.CallOption) (*LotteryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LotteryResp)
	err := c.cc.Invoke(ctx, LotteryService_Lottery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotteryServiceClient) GetGameState(ctx context.Context, in *GetGameStateReq, opts ...grpc.CallOption) (*GetGameStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStateResp)
	err := c.cc.Invoke(ctx, LotteryService_GetGameState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotteryServiceServer is the server API for LotteryService service.
// All implementations must embed UnimplementedLotteryServiceServer
// for forward compatibility.
type LotteryServiceServer interface {
	// Lottery
	Lottery(context.Context, *LotteryReq) (*LotteryResp, error)
	// 获取游戏记录
	GetGameState(context.Context, *GetGameStateReq) (*GetGameStateResp, error)
	mustEmbedUnimplementedLotteryServiceServer()
}

// UnimplementedLotteryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotteryServiceServer struct{}

func (UnimplementedLotteryServiceServer) Lottery(context.Context, *LotteryReq) (*LotteryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Lottery not implemented")
}
func (UnimplementedLotteryServiceServer) GetGameState(context.Context, *GetGameStateReq) (*GetGameStateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameState not implemented")
}
func (UnimplementedLotteryServiceServer) mustEmbedUnimplementedLotteryServiceServer() {}
func (UnimplementedLotteryServiceServer) testEmbeddedByValue()                        {}

// UnsafeLotteryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotteryServiceServer will
// result in compilation errors.
type UnsafeLotteryServiceServer interface {
	mustEmbedUnimplementedLotteryServiceServer()
}

func RegisterLotteryServiceServer(s grpc.ServiceRegistrar, srv LotteryServiceServer) {
	// If the following call panics, it indicates UnimplementedLotteryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotteryService_ServiceDesc, srv)
}

func _LotteryService_Lottery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LotteryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).Lottery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_Lottery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).Lottery(ctx, req.(*LotteryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotteryService_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotteryServiceServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotteryService_GetGameState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotteryServiceServer).GetGameState(ctx, req.(*GetGameStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LotteryService_ServiceDesc is the grpc.ServiceDesc for LotteryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotteryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lottery.LotteryService",
	HandlerType: (*LotteryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lottery",
			Handler:    _LotteryService_Lottery_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _LotteryService_GetGameState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lottery.proto",
}
