// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: lottery.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGameStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateReq) Reset() {
	*x = GetGameStateReq{}
	mi := &file_lottery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateReq) ProtoMessage() {}

func (x *GetGameStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateReq.ProtoReflect.Descriptor instead.
func (*GetGameStateReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameStateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGameStateReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetGameStateReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetGameStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResp) Reset() {
	*x = GetGameStateResp{}
	mi := &file_lottery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResp) ProtoMessage() {}

func (x *GetGameStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResp.ProtoReflect.Descriptor instead.
func (*GetGameStateResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameStateResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

func (x *GetGameStateResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SaveGameStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameStateReq) Reset() {
	*x = SaveGameStateReq{}
	mi := &file_lottery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameStateReq) ProtoMessage() {}

func (x *SaveGameStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameStateReq.ProtoReflect.Descriptor instead.
func (*SaveGameStateReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{2}
}

func (x *SaveGameStateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveGameStateReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SaveGameStateReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SaveGameStateReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SaveGameStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameStateResp) Reset() {
	*x = SaveGameStateResp{}
	mi := &file_lottery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameStateResp) ProtoMessage() {}

func (x *SaveGameStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameStateResp.ProtoReflect.Descriptor instead.
func (*SaveGameStateResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{3}
}

func (x *SaveGameStateResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

type LotteryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	CurrencyType  string                 `protobuf:"bytes,5,opt,name=currencyType,proto3" json:"currencyType,omitempty"`
	AgentId       int64                  `protobuf:"varint,6,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Symbol        string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ProfitLoss    string                 `protobuf:"bytes,8,opt,name=profitLoss,proto3" json:"profitLoss,omitempty"`        //开奖
	Bet           string                 `protobuf:"bytes,9,opt,name=bet,proto3" json:"bet,omitempty"`                      //下注
	State         string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`                 //状态
	Token         string                 `protobuf:"bytes,11,opt,name=token,proto3" json:"token,omitempty"`                 //token
	RoundID       string                 `protobuf:"bytes,12,opt,name=roundID,proto3" json:"roundID,omitempty"`             //局号 --下注时使用
	MaxProfitLoss string                 `protobuf:"bytes,13,opt,name=maxProfitLoss,proto3" json:"maxProfitLoss,omitempty"` //最大赔付
	Complete      bool                   `protobuf:"varint,14,opt,name=complete,proto3" json:"complete,omitempty"`          //注单是否结束
	Account       string                 `protobuf:"bytes,15,opt,name=account,proto3" json:"account,omitempty"`             //三方平台账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotteryReq) Reset() {
	*x = LotteryReq{}
	mi := &file_lottery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryReq) ProtoMessage() {}

func (x *LotteryReq) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryReq.ProtoReflect.Descriptor instead.
func (*LotteryReq) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{4}
}

func (x *LotteryReq) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LotteryReq) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *LotteryReq) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *LotteryReq) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *LotteryReq) GetProfitLoss() string {
	if x != nil {
		return x.ProfitLoss
	}
	return ""
}

func (x *LotteryReq) GetBet() string {
	if x != nil {
		return x.Bet
	}
	return ""
}

func (x *LotteryReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LotteryReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LotteryReq) GetRoundID() string {
	if x != nil {
		return x.RoundID
	}
	return ""
}

func (x *LotteryReq) GetMaxProfitLoss() string {
	if x != nil {
		return x.MaxProfitLoss
	}
	return ""
}

func (x *LotteryReq) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *LotteryReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type LotteryResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家最新的金币数
	NewCurrency string `protobuf:"bytes,1,opt,name=newCurrency,proto3" json:"newCurrency,omitempty"`
	Result      bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	// 当前可赔付值
	Pay           string    `protobuf:"bytes,3,opt,name=pay,proto3" json:"pay,omitempty"`
	Code          ErrorCode `protobuf:"varint,4,opt,name=code,proto3,enum=base.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotteryResp) Reset() {
	*x = LotteryResp{}
	mi := &file_lottery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryResp) ProtoMessage() {}

func (x *LotteryResp) ProtoReflect() protoreflect.Message {
	mi := &file_lottery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryResp.ProtoReflect.Descriptor instead.
func (*LotteryResp) Descriptor() ([]byte, []int) {
	return file_lottery_proto_rawDescGZIP(), []int{5}
}

func (x *LotteryResp) GetNewCurrency() string {
	if x != nil {
		return x.NewCurrency
	}
	return ""
}

func (x *LotteryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *LotteryResp) GetPay() string {
	if x != nil {
		return x.Pay
	}
	return ""
}

func (x *LotteryResp) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_OK
}

var File_lottery_proto protoreflect.FileDescriptor

const file_lottery_proto_rawDesc = "" +
	"\n" +
	"\rlottery.proto\x12\alottery\x1a\n" +
	"base.proto\"]\n" +
	"\x0fGetGameStateReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"L\n" +
	"\x10GetGameStateResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"r\n" +
	"\x10SaveGameStateReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"9\n" +
	"\x11SaveGameStateResp\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.base.error_codeR\x04code\"\xd2\x02\n" +
	"\n" +
	"LotteryReq\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\rR\bplayerId\x12\"\n" +
	"\fcurrencyType\x18\x05 \x01(\tR\fcurrencyType\x12\x18\n" +
	"\aagentId\x18\x06 \x01(\x03R\aagentId\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"profitLoss\x18\b \x01(\tR\n" +
	"profitLoss\x12\x10\n" +
	"\x03bet\x18\t \x01(\tR\x03bet\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x14\n" +
	"\x05token\x18\v \x01(\tR\x05token\x12\x18\n" +
	"\aroundID\x18\f \x01(\tR\aroundID\x12$\n" +
	"\rmaxProfitLoss\x18\r \x01(\tR\rmaxProfitLoss\x12\x1a\n" +
	"\bcomplete\x18\x0e \x01(\bR\bcomplete\x12\x18\n" +
	"\aaccount\x18\x0f \x01(\tR\aaccount\"\x7f\n" +
	"\vLotteryResp\x12 \n" +
	"\vnewCurrency\x18\x01 \x01(\tR\vnewCurrency\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\x12\x10\n" +
	"\x03pay\x18\x03 \x01(\tR\x03pay\x12$\n" +
	"\x04code\x18\x04 \x01(\x0e2\x10.base.error_codeR\x04code2\x8b\x01\n" +
	"\x0eLotteryService\x124\n" +
	"\aLottery\x12\x13.lottery.LotteryReq\x1a\x14.lottery.LotteryResp\x12C\n" +
	"\fGetGameState\x12\x18.lottery.GetGameStateReq\x1a\x19.lottery.GetGameStateRespB\x15Z\x13./services;servicesb\x06proto3"

var (
	file_lottery_proto_rawDescOnce sync.Once
	file_lottery_proto_rawDescData []byte
)

func file_lottery_proto_rawDescGZIP() []byte {
	file_lottery_proto_rawDescOnce.Do(func() {
		file_lottery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)))
	})
	return file_lottery_proto_rawDescData
}

var file_lottery_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lottery_proto_goTypes = []any{
	(*GetGameStateReq)(nil),   // 0: lottery.GetGameStateReq
	(*GetGameStateResp)(nil),  // 1: lottery.GetGameStateResp
	(*SaveGameStateReq)(nil),  // 2: lottery.SaveGameStateReq
	(*SaveGameStateResp)(nil), // 3: lottery.SaveGameStateResp
	(*LotteryReq)(nil),        // 4: lottery.LotteryReq
	(*LotteryResp)(nil),       // 5: lottery.LotteryResp
	(ErrorCode)(0),            // 6: base.error_code
}
var file_lottery_proto_depIdxs = []int32{
	6, // 0: lottery.GetGameStateResp.code:type_name -> base.error_code
	6, // 1: lottery.SaveGameStateResp.code:type_name -> base.error_code
	6, // 2: lottery.LotteryResp.code:type_name -> base.error_code
	4, // 3: lottery.LotteryService.Lottery:input_type -> lottery.LotteryReq
	0, // 4: lottery.LotteryService.GetGameState:input_type -> lottery.GetGameStateReq
	5, // 5: lottery.LotteryService.Lottery:output_type -> lottery.LotteryResp
	1, // 6: lottery.LotteryService.GetGameState:output_type -> lottery.GetGameStateResp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lottery_proto_init() }
func file_lottery_proto_init() {
	if File_lottery_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lottery_proto_rawDesc), len(file_lottery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lottery_proto_goTypes,
		DependencyIndexes: file_lottery_proto_depIdxs,
		MessageInfos:      file_lottery_proto_msgTypes,
	}.Build()
	File_lottery_proto = out.File
	file_lottery_proto_goTypes = nil
	file_lottery_proto_depIdxs = nil
}
