// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HumanPlayer struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	GameCurrency         string   `protobuf:"bytes,3,opt,name=GameCurrency,proto3" json:"GameCurrency,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender               uint32   `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Exp                  uint32   `protobuf:"varint,6,opt,name=Exp,proto3" json:"Exp,omitempty"`
	AgentId              uint32   `protobuf:"varint,7,opt,name=AgentId,proto3" json:"AgentId,omitempty"`
	LoginIP              string   `protobuf:"bytes,8,opt,name=LoginIP,proto3" json:"LoginIP,omitempty"`
	LoginTimeStamp       int64    `protobuf:"varint,9,opt,name=LoginTimeStamp,proto3" json:"LoginTimeStamp,omitempty"`
	CurrencyLimit        string   `protobuf:"bytes,10,opt,name=CurrencyLimit,proto3" json:"CurrencyLimit,omitempty"`
	WebSiteId            uint32   `protobuf:"varint,11,opt,name=WebSiteId,proto3" json:"WebSiteId,omitempty"`
	Factory              uint32   `protobuf:"varint,12,opt,name=Factory,proto3" json:"Factory,omitempty"`
	HeadFrame            string   `protobuf:"bytes,13,opt,name=head_frame,json=headFrame,proto3" json:"head_frame,omitempty"`
	Account              string   `protobuf:"bytes,14,opt,name=Account,proto3" json:"Account,omitempty"`
	CurrencyType         string   `protobuf:"bytes,15,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	Points               string   `protobuf:"bytes,16,opt,name=points,proto3" json:"points,omitempty"`
	Value                string   `protobuf:"bytes,17,opt,name=value,proto3" json:"value,omitempty"`
	Reward               string   `protobuf:"bytes,18,opt,name=reward,proto3" json:"reward,omitempty"`
	AllTimes             int32    `protobuf:"varint,19,opt,name=all_times,json=allTimes,proto3" json:"all_times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HumanPlayer) Reset()         { *m = HumanPlayer{} }
func (m *HumanPlayer) String() string { return proto.CompactTextString(m) }
func (*HumanPlayer) ProtoMessage()    {}
func (*HumanPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *HumanPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HumanPlayer.Unmarshal(m, b)
}
func (m *HumanPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HumanPlayer.Marshal(b, m, deterministic)
}
func (m *HumanPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HumanPlayer.Merge(m, src)
}
func (m *HumanPlayer) XXX_Size() int {
	return xxx_messageInfo_HumanPlayer.Size(m)
}
func (m *HumanPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_HumanPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_HumanPlayer proto.InternalMessageInfo

func (m *HumanPlayer) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HumanPlayer) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *HumanPlayer) GetGameCurrency() string {
	if m != nil {
		return m.GameCurrency
	}
	return ""
}

func (m *HumanPlayer) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *HumanPlayer) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *HumanPlayer) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *HumanPlayer) GetAgentId() uint32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *HumanPlayer) GetLoginIP() string {
	if m != nil {
		return m.LoginIP
	}
	return ""
}

func (m *HumanPlayer) GetLoginTimeStamp() int64 {
	if m != nil {
		return m.LoginTimeStamp
	}
	return 0
}

func (m *HumanPlayer) GetCurrencyLimit() string {
	if m != nil {
		return m.CurrencyLimit
	}
	return ""
}

func (m *HumanPlayer) GetWebSiteId() uint32 {
	if m != nil {
		return m.WebSiteId
	}
	return 0
}

func (m *HumanPlayer) GetFactory() uint32 {
	if m != nil {
		return m.Factory
	}
	return 0
}

func (m *HumanPlayer) GetHeadFrame() string {
	if m != nil {
		return m.HeadFrame
	}
	return ""
}

func (m *HumanPlayer) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *HumanPlayer) GetCurrencyType() string {
	if m != nil {
		return m.CurrencyType
	}
	return ""
}

func (m *HumanPlayer) GetPoints() string {
	if m != nil {
		return m.Points
	}
	return ""
}

func (m *HumanPlayer) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *HumanPlayer) GetReward() string {
	if m != nil {
		return m.Reward
	}
	return ""
}

func (m *HumanPlayer) GetAllTimes() int32 {
	if m != nil {
		return m.AllTimes
	}
	return 0
}

type PlayerStatistics struct {
	Times                uint32   `protobuf:"varint,2,opt,name=times,proto3" json:"times,omitempty"`
	Bet                  uint32   `protobuf:"varint,3,opt,name=bet,proto3" json:"bet,omitempty"`
	Incr                 uint32   `protobuf:"varint,4,opt,name=incr,proto3" json:"incr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStatistics) Reset()         { *m = PlayerStatistics{} }
func (m *PlayerStatistics) String() string { return proto.CompactTextString(m) }
func (*PlayerStatistics) ProtoMessage()    {}
func (*PlayerStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *PlayerStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStatistics.Unmarshal(m, b)
}
func (m *PlayerStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStatistics.Marshal(b, m, deterministic)
}
func (m *PlayerStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStatistics.Merge(m, src)
}
func (m *PlayerStatistics) XXX_Size() int {
	return xxx_messageInfo_PlayerStatistics.Size(m)
}
func (m *PlayerStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStatistics proto.InternalMessageInfo

func (m *PlayerStatistics) GetTimes() uint32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func (m *PlayerStatistics) GetBet() uint32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

func (m *PlayerStatistics) GetIncr() uint32 {
	if m != nil {
		return m.Incr
	}
	return 0
}

func init() {
	proto.RegisterType((*HumanPlayer)(nil), "services.HumanPlayer")
	proto.RegisterType((*PlayerStatistics)(nil), "services.PlayerStatistics")
}

func init() { proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6) }

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x6f, 0x8b, 0xd3, 0x40,
	0x10, 0x87, 0x49, 0xaf, 0xed, 0x35, 0x73, 0x4d, 0xad, 0xa3, 0xc8, 0xe0, 0x1f, 0x28, 0x55, 0xa4,
	0xaf, 0x7c, 0xe3, 0x27, 0x38, 0xc4, 0x3b, 0x03, 0xc7, 0x71, 0xa4, 0x07, 0xbe, 0x2c, 0xdb, 0xcd,
	0x78, 0x2e, 0x26, 0x9b, 0xb0, 0xd9, 0x56, 0xf3, 0x55, 0xfc, 0xb4, 0xb2, 0xb3, 0xa9, 0x72, 0xbe,
	0x9b, 0xe7, 0x99, 0x65, 0xf2, 0xcb, 0xec, 0xc2, 0xbc, 0xad, 0x54, 0xcf, 0xee, 0x43, 0xeb, 0x1a,
	0xdf, 0xe0, 0xac, 0x63, 0x77, 0x34, 0x9a, 0xbb, 0xf5, 0xef, 0x31, 0x5c, 0x7c, 0x39, 0xd4, 0xca,
	0xde, 0x49, 0x1f, 0x17, 0x30, 0xca, 0x4b, 0x4a, 0x56, 0xc9, 0x26, 0x2b, 0x46, 0x79, 0x89, 0x2f,
	0x61, 0x76, 0x6b, 0xf4, 0x0f, 0xab, 0x6a, 0xa6, 0xd1, 0x2a, 0xd9, 0xa4, 0xc5, 0x5f, 0xc6, 0x35,
	0xcc, 0xaf, 0x55, 0xcd, 0x9f, 0x0e, 0xce, 0xb1, 0xd5, 0x3d, 0x9d, 0x49, 0xff, 0x91, 0xc3, 0x17,
	0x30, 0xbd, 0x3c, 0x2a, 0xaf, 0x1c, 0x8d, 0xa5, 0x3b, 0x50, 0xf0, 0xd7, 0x6c, 0x4b, 0x76, 0x34,
	0x91, 0x6f, 0x0d, 0x84, 0x4b, 0x38, 0xfb, 0xfc, 0xab, 0xa5, 0xa9, 0xc8, 0x50, 0x22, 0xc1, 0xf9,
	0xe5, 0x03, 0x5b, 0x9f, 0x97, 0x74, 0x2e, 0xf6, 0x84, 0xa1, 0x73, 0xd3, 0x3c, 0x18, 0x9b, 0xdf,
	0xd1, 0x4c, 0x86, 0x9f, 0x10, 0xdf, 0xc3, 0x42, 0xca, 0x7b, 0x53, 0xf3, 0xd6, 0xab, 0xba, 0xa5,
	0x74, 0x95, 0x6c, 0xce, 0x8a, 0xff, 0x2c, 0xbe, 0x83, 0xec, 0x94, 0xf4, 0xc6, 0xd4, 0xc6, 0x13,
	0xc8, 0x9c, 0xc7, 0x12, 0x5f, 0x43, 0xfa, 0x95, 0xf7, 0x5b, 0xe3, 0x39, 0x2f, 0xe9, 0x42, 0x32,
	0xfc, 0x13, 0x21, 0xc5, 0x95, 0xd2, 0xbe, 0x71, 0x3d, 0xcd, 0x63, 0xbe, 0x01, 0xf1, 0x0d, 0xc0,
	0x77, 0x56, 0xe5, 0xee, 0x9b, 0x0b, 0xdb, 0xcb, 0x64, 0x74, 0x1a, 0xcc, 0x55, 0x10, 0xf2, 0x63,
	0x5a, 0x37, 0x07, 0xeb, 0x69, 0x11, 0xe3, 0x0f, 0x88, 0x6f, 0x21, 0xd3, 0x43, 0x82, 0x9d, 0xef,
	0x5b, 0xa6, 0x27, 0x71, 0xb3, 0x27, 0x79, 0xdf, 0xb7, 0x1c, 0x36, 0xd8, 0x36, 0xc6, 0xfa, 0x8e,
	0x96, 0x71, 0xb3, 0x91, 0xf0, 0x39, 0x4c, 0x8e, 0xaa, 0x3a, 0x30, 0x3d, 0x15, 0x1d, 0x21, 0x9c,
	0x76, 0xfc, 0x53, 0xb9, 0x92, 0x30, 0x9e, 0x8e, 0x84, 0xaf, 0x20, 0x55, 0x55, 0xb5, 0xf3, 0xa6,
	0xe6, 0x8e, 0x9e, 0xad, 0x92, 0xcd, 0xa4, 0x98, 0xa9, 0xaa, 0x0a, 0x2b, 0xea, 0xd6, 0xb7, 0xb0,
	0x8c, 0xcf, 0x62, 0xeb, 0x95, 0x37, 0x9d, 0x37, 0x5a, 0xc6, 0xc7, 0xc3, 0x23, 0xf9, 0xd9, 0x08,
	0xe1, 0xda, 0xf6, 0xec, 0xe5, 0x05, 0x64, 0x45, 0x28, 0x11, 0x61, 0x6c, 0xac, 0x8e, 0xd7, 0x9e,
	0x15, 0x52, 0xef, 0xa7, 0xf2, 0xfa, 0x3e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x43, 0xc4,
	0x95, 0x8d, 0x02, 0x00, 0x00,
}
